task1a:
	@gcc -o task1_exe task1.c

run1a: 
	@./task1_exe

task1b:
	@gcc -o task1b_exe task1b.c

run1b:
	@./task1b_exe

task2:
	@gcc -o task2_exe task2.c

run2:
	@./task2_exe

task3:
	@gcc -o task3_exe task3.c

run3:
	@./task3_exe

task4:
	@gcc -o task4_exe task4.c

run4:
	@./task4_exe

task5:
	@gcc -o task5_exe task5.c

run5:
	@./task5_exe
